#!/usr/bin/env bash
############################################################ /ᐠ｡ꞈ｡ᐟ\############################################################
#Developed by: Tal Mendelson
#Purpose: This script is used by setup.sh script to check for Ngnix, and install of missing.
#Date:07/03/2025
#Version: 0.0.1
############################################################ /ᐠ｡ꞈ｡ᐟ\ ############################################################

function CHECK_NGINX(){
    # Checks if not already installed
    if ! command -v nginx &> /dev/null; then
        printf "\n${BOLD}Do you wish to install Nginx on this machine?${RESET}\n\n"
        # Choices - Intall Ngnix
        printf "# ============================= #\n"
        printf "1) ${BLUE}Install Ngnix.${RESET}\n"
        printf "2) ${BLUE}Cancel.${RESET}\n"
        printf "# ============================= #\n\n"

        # User selection
        printf "${BOLD}Do you wish to install Nginx?${RESET} (1 = Yes / 2 = No ) " && read ngnix_install_choice
        case "$ngnix_install_choice" in
            1) 
                # Install.
                apt update && apt install -y nginx
                ## Check status
                    if command -v nginx > /dev/null 2>&1; then
                        printf "\n${BOLD}${GREEN}Nginx installation completed successfully.${RESET}\n\n"
                        nginx -v
                    else
                        printf "\n${BOLD}${RED}ERROR - Something went wrong.${RESET}\n\n"
                    fi
            ;;
            2)
                # Cancel.
                printf "Ngnix installation canceled, exiting script.\n\n"
                exit 0
            ;;
            *)
                # Invalid option.
                printf "\n${RED}${BOLD}Invalid option.${RESET}\n"
                exit 1
            ;;
        esac

    else # Installed
        printf "\n${BOLD}${GREEN}Ngnix installation detected:${RESET}\n"
        nginx -v
        printf "\nExiting Script...\n"
    fi
}